/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#292a2d',
        'outline': '#8b90a0',
        'on-error': '#690005',
        'tertiary': '#ffb59e',
        'on-secondary': '#053900',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#001a41',
        'tertiary-container': '#ff5719',
        'surface-tint': '#adc7ff',
        'on-tertiary': '#5e1700',
        'error-container': '#93000a',
        'on-secondary-container': '#0f6d00',
        'error': '#ffb4ab',
        'secondary': '#d7ffc5',
        'surface-container-low': '#1a1b1e',
        'surface-container': '#1f1f23',
        'surface-variant': '#343538',
        'primary-container': '#4a8eff',
        'on-primary-fixed-variant': '#004493',
        'surface': '#121316',
        'secondary-container': '#2ff801',
        'tertiary-fixed-dim': '#ffb59e',
        'on-tertiary-container': '#521300',
        'on-surface': '#e3e2e6',
        'surface-dim': '#121316',
        'on-primary-container': '#00285b',
        'surface-container-lowest': '#0d0e11',
        'on-surface-variant': '#c1c6d7',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc7ff',
        'on-background': '#e3e2e6',
        'surface-bright': '#38393c',
        'inverse-on-surface': '#2f3033',
        'on-primary': '#002e68',
        'on-tertiary-fixed-variant': '#852400',
        'inverse-primary': '#005bc0',
        'on-secondary-fixed': '#022100',
        'tertiary-fixed': '#ffdbd0',
        'primary': '#adc7ff',
        'background': '#121316',
        'outline-variant': '#414754',
        'secondary-fixed': '#79ff5b',
        'inverse-surface': '#e3e2e6',
        'on-tertiary-fixed': '#3a0b00',
        'surface-container-highest': '#343538',
        // Legacy compat
        brand: {
          300: '#adc7ff',
          400: '#4a8eff',
          500: '#adc7ff',
          600: '#005bc0',
        },
        dark: {
          900: '#0d0e11',
          950: '#121316',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        headline: ['Geist', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'code-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'code-base': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.15s ease-out',
        'slide-up': 'slideUp 0.2s ease-out',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'blink': 'blink 1s step-end infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(6px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
